import { HugeiconsIcon } from "@hugeicons/react";
import {
  Bookmark02Icon,
  Copy01Icon,
  Copy02Icon,
  Delete01Icon,
  FileAttachmentIcon,
  Link04Icon,
  PencilEdit02Icon,
  PlayCircleIcon,
  PlusSignCircleIcon,
} from "@hugeicons/core-free-icons/index";

import {
  handleAddContextMenu,
  handleContextMenuCopyClass,
  handleContextMenuCopyParentClass,
  handleCopyAnimContextMenu,
  handleDeleteAnimContextMenu,
  handleEditAnimContextMenu,
  handleInspect,
  handlePasteAnimContextMenu,
  handlePreviewAnimContextMenu,
  handleSaveAnimContextMenu,
} from "@/lib/editor/contextMenu/contextMenuEventTrigger";

export const menuItems = [
  {
    contextMenuKey: "wcf-cmb-copy-class",
    icon: <HugeiconsIcon icon={Copy01Icon} />,
    title: "Copy Class",
    trigger: [],
    options: [],
    callback: handleContextMenuCopyClass,
  },
  {
    contextMenuKey: "wcf-cmb-copy-parent-class",
    icon: <HugeiconsIcon icon={Copy02Icon} />,
    title: "Copy Parent Class",
    trigger: [],
    options: [],
    callback: handleContextMenuCopyParentClass,
  },
  {
    contextMenuKey: "wcf-cmb-add-animation",
    icon: <HugeiconsIcon icon={PlusSignCircleIcon} />,
    title: "Add Animation",
    trigger: [],
    options: [
      {
        contextMenuKey: "wcf-cmb-add-anim-current",
        icon: "",
        title: "Current Animation",
        trigger: [],
        options: [
          {
            contextMenuKey: "wcf-ab-ca-classic",
            icon: "",
            title: "Classic Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
          {
            contextMenuKey: "wcf-ab-ca-preset",
            icon: "",
            title: "Preset Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
          {
            contextMenuKey: "wcf-ab-ca-custom",
            icon: "",
            title: "Custom Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
        ],
        callback: null,
      },
      {
        contextMenuKey: "wcf-cmb-add-anim-current",
        icon: "",
        title: "Global Animation",
        trigger: [],
        options: [
          {
            contextMenuKey: "wcf-ab-ca-classic",
            icon: "",
            title: "Classic Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
          {
            contextMenuKey: "wcf-ab-ca-preset",
            icon: "",
            title: "Preset Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
          {
            contextMenuKey: "wcf-ab-ca-custom",
            icon: "",
            title: "Custom Animation",
            trigger: [],
            options: [],
            callback: handleAddContextMenu,
          },
        ],
        callback: (e) => {
          console.log("global animation", e);
        },
      },
    ],
    callback: null,
  },
  {
    contextMenuKey: "wcf-cmb-edit-animation",
    icon: <HugeiconsIcon icon={PencilEdit02Icon} />,
    title: "Edit Animation",
    trigger: [],
    options: [],
    callback: handleEditAnimContextMenu,
  },
  {
    contextMenuKey: "wcf-cmb-preview-animation",
    icon: <HugeiconsIcon icon={PlayCircleIcon} />,
    title: "Preview Animation",
    trigger: [],
    options: [],
    callback: handlePreviewAnimContextMenu,
  },
  {
    contextMenuKey: "wcf-cmb-copy-animation",
    icon: <HugeiconsIcon icon={Link04Icon} />,
    title: "Copy Animation",
    trigger: [],
    options: [],
    callback: handleCopyAnimContextMenu,
  },
  {
    contextMenuKey: "wcf-cmb-paste-animation",
    icon: <HugeiconsIcon icon={FileAttachmentIcon} />,
    title: "Paste Animation",
    trigger: [],
    options: [],
    callback: handlePasteAnimContextMenu,
  },
  {
    contextMenuKey: "wcf-cmb-delete-animation",
    icon: <HugeiconsIcon icon={Delete01Icon} />,
    title: "Delete Animation",
    trigger: [],
    options: [],
    callback: handleDeleteAnimContextMenu,
  },
  {
    contextMenuKey: "wcf-cmb-save-animation",
    icon: <HugeiconsIcon icon={Bookmark02Icon} />,
    title: "Save Animation",
    trigger: [],
    options: [],
    callback: handleSaveAnimContextMenu,
  },
];
